# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\exporting_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Exporting_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(419, 313)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icons/export_106661.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("\n"
"QToolTip\n"
"{\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 0.5ex;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #31363B;\n"
"    background-color: #EFF0F1;\n"
"    selection-background-color:#33A4DF;\n"
"    selection-color: #31363B;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    border: 0px transparent black;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: #33A4DF;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: #33A4DF;\n"
"}\n"
"\n"
"\n"
"QCheckBox\n"
"{\n"
"    spacing: 0.5ex;\n"
"    outline: none;\n"
"    color: #31363B;\n"
"    margin-bottom: 0.2ex;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"    color: #BAB9B8;\n"
"}\n"
"\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 0.2ex;\n"
"    margin-left: 0.2ex;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked,\n"
"QCheckBox::indicator:unchecked:focus\n"
"{\n"
"    border-image: url(:/light/checkbox_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover,\n"
"QCheckBox::indicator:unchecked:pressed,\n"
"QGroupBox::indicator:unchecked:hover,\n"
"QGroupBox::indicator:unchecked:focus,\n"
"QGroupBox::indicator:unchecked:pressed\n"
"{\n"
"    border: none;\n"
"    border-image: url(:/light/checkbox_unchecked-hover.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    border-image: url(:/light/checkbox_checked.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:focus,\n"
"QCheckBox::indicator:checked:pressed,\n"
"QGroupBox::indicator:checked:focus,\n"
"QGroupBox::indicator:checked:pressed\n"
"{\n"
"    border: none;\n"
"    border-image: url(:/light/checkbox_checked.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover,\n"
"QGroupBox::indicator:checked:hover\n"
"{\n"
"    border-image: url(:/light/checkbox_checked-hover.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate\n"
"{\n"
"    border-image: url(:/light/checkbox_indeterminate.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:hover\n"
"{\n"
"    border-image: url(:/light/checkbox_indeterminate-hover.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:focus,\n"
"QCheckBox::indicator:indeterminate:pressed\n"
"{\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:disabled\n"
"{\n"
"    border-image: url(:/light/checkbox_indeterminate_disabled.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled,\n"
"QGroupBox::indicator:checked:disabled\n"
"{\n"
"    border-image: url(:/light/checkbox_checked_disabled.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:disabled,\n"
"QGroupBox::indicator:unchecked:disabled\n"
"{\n"
"    border-image: url(:/light/checkbox_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QRadioButton\n"
"{\n"
"    spacing: 0.5ex;\n"
"    outline: none;\n"
"    color: #31363B;\n"
"    margin-bottom: 0.2ex;\n"
"}\n"
"\n"
"QRadioButton:disabled\n"
"{\n"
"    color: #BAB9B8;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked,\n"
"QRadioButton::indicator:unchecked:focus\n"
"{\n"
"    border-image: url(:/light/radio_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover,\n"
"QRadioButton::indicator:unchecked:pressed\n"
"{\n"
"    border: none;\n"
"    outline: none;\n"
"    border-image: url(:/light/radio_unchecked-hover.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    border: none;\n"
"    outline: none;\n"
"    border-image: url(:/light/radio_checked.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:focus,\n"
"QRadioButton::indicator:checked:pressed\n"
"{\n"
"    border: none;\n"
"    outline: none;\n"
"    border-image: url(:/light/radio_checked.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover\n"
"{\n"
"    border-image: url(:/light/radio_checked-hover.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disabled\n"
"{\n"
"    outline: none;\n"
"    border-image: url(:/light/radio_checked_disabled.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:disabled\n"
"{\n"
"    border-image: url(:/light/radio_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QMenuBar\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    background-color: #33A4DF;\n"
"    color: #31363B;\n"
"    margin-bottom: -0.1ex;\n"
"    padding-bottom: 0.1ex;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    color: #31363B;\n"
"    margin: 0.2ex;\n"
"}\n"
"\n"
"QMenu::icon\n"
"{\n"
"    margin: 0.5ex;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 0.5ex 3ex 0.5ex 3ex;\n"
"    margin-left: 0.5ex;\n"
"    border: 0.1ex solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 0.2ex;\n"
"    background: lightblue;\n"
"    margin-left: 1ex;\n"
"    margin-right: 0.5ex;\n"
"}\n"
"\n"
"/* non-exclusive indicator = check box style indicator\n"
"   (see QActionGroup::setExclusive) */\n"
"QMenu::indicator:non-exclusive:unchecked\n"
"{\n"
"    border-image: url(:/light/checkbox_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:selected\n"
"{\n"
"    border-image: url(:/light/checkbox_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked\n"
"{\n"
"    border-image: url(:/light/checkbox_checked.svg);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:selected\n"
"{\n"
"    border-image: url(:/light/checkbox_checked.svg);\n"
"}\n"
"\n"
"/* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"QMenu::indicator:exclusive:unchecked\n"
"{\n"
"    border-image: url(:/light/radio_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:selected\n"
"{\n"
"    border-image: url(:/light/radio_unchecked_disabled.svg);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked\n"
"{\n"
"    border-image: url(:/light/radio_checked.svg);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:selected\n"
"{\n"
"    border-image: url(:/light/radio_checked.svg);\n"
"}\n"
"\n"
"QMenu::right-arrow\n"
"{\n"
"    margin: 0.5ex;\n"
"    border-image: url(:/light/right_arrow.svg);\n"
"    width: 0.6ex;\n"
"    height: 0.9ex;\n"
"}\n"
"\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #454545;\n"
"    background-color: #EFF0F1;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    alternate-background-color: #EFF0F1;\n"
"    color: #31363B;\n"
"    border: 0.1ex solid 3A3939;\n"
"    border-radius: 0.2ex;\n"
"}\n"
"\n"
"QWidget:focus,\n"
"QMenuBar:focus\n"
"{\n"
"    border: 0.1ex solid #33A4DF;\n"
"}\n"
"\n"
"QTabWidget:focus,\n"
"QCheckBox:focus,\n"
"QRadioButton:focus,\n"
"QSlider:focus\n"
"{\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: #FCFCFC;\n"
"    padding: 0.5ex;\n"
"    border-style: solid;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    border-radius: 0.2ex;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    border-radius: 0.2ex;\n"
"    padding-top: 1ex;\n"
"    margin-top: 1ex;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding-left: 0.1ex;\n"
"    padding-right: 0.1ex;\n"
"    margin-top: -0.7ex;\n"
"}\n"
"\n"
"QAbstractScrollArea\n"
"{\n"
"    border-radius: 0.2ex;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    height: 1.5ex;\n"
"    margin: 0.3ex 1.5ex 0.3ex 1.5ex;\n"
"    border: 0.1ex transparent #2A2929;\n"
"    border-radius: 0.4ex;\n"
"    background-color: #2A2929;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-width: 0.5ex;\n"
"    border-radius: 0.4ex;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    margin: 0ex 0.3ex 0ex 0.3ex;\n"
"    border-image: url(:/light/right_arrow_disabled.svg);\n"
"    width: 1ex;\n"
"    height: 1ex;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    margin: 0px 0.3ex 0px 0.3ex;\n"
"    border-image: url(:/light/left_arrow_disabled.svg);\n"
"    height: 1ex;\n"
"    width: 1ex;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
"{\n"
"    border-image: url(:/light/right_arrow.svg);\n"
"    width: 1ex;\n"
"    height: 1ex;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
"{\n"
"    border-image: url(:/light/left_arrow.svg);\n"
"    width: 1ex;\n"
"    height: 1ex;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #2A2929;\n"
"    width: 1.5ex;\n"
"    margin: 1.5ex 0.3ex 1.5ex 0.3ex;\n"
"    border: 0.1ex transparent #2A2929;\n"
"    border-radius: 0.4ex;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-height: 0.5ex;\n"
"    border-radius: 0.4ex;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    margin: 0.3ex 0ex 0.3ex 0ex;\n"
"    border-image: url(:/light/up_arrow_disabled.svg);\n"
"    height: 1ex;\n"
"    width: 1ex;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    margin: 0.3ex 0ex 0.3ex 0ex;\n"
"    border-image: url(:/light/down_arrow_disabled.svg);\n"
"    height: 1ex;\n"
"    width: 1ex;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::sub-line:vertical:on\n"
"{\n"
"\n"
"    border-image: url(:/light/up_arrow.svg);\n"
"    height: 1ex;\n"
"    width: 1ex;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover,\n"
"QScrollBar::add-line:vertical:on\n"
"{\n"
"    border-image: url(:/light/down_arrow.svg);\n"
"    height: 1ex;\n"
"    width: 1ex;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    color: #31363B;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    color: #31363B;\n"
"    border-radius: 0.2ex;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #BAB9B8;\n"
"    color: #31363B;\n"
"    padding: 0.5ex;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QSizeGrip\n"
"{\n"
"    border-image: url(:/light/sizegrip.svg);\n"
"    width: 1.2ex;\n"
"    height: 1.2ex;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    color: white;\n"
"    padding-left: 0.4ex;\n"
"    spacing: 0.2ex;\n"
"    border: 0.1ex dashed #BAB9B8;\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: #787876;\n"
"    color: white;\n"
"    padding-left: 0.4ex;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    spacing: 0.2x;\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 0.1ex;\n"
"    background-color: #BAB9B8;\n"
"    color: white;\n"
"    padding-left: 0.4ex;\n"
"    margin-left: 1ex;\n"
"    margin-right: 0.5ex;\n"
"}\n"
"\n"
"QFrame[frameShape=\"2\"],  /* QFrame::Panel == 0x0003 */\n"
"QFrame[frameShape=\"3\"],  /* QFrame::WinPanel == 0x0003 */\n"
"QFrame[frameShape=\"4\"],  /* QFrame::HLine == 0x0004 */\n"
"QFrame[frameShape=\"5\"],  /* QFrame::VLine == 0x0005 */\n"
"QFrame[frameShape=\"6\"]  /* QFrame::StyledPanel == 0x0006 */\n"
"{\n"
"    border-width: 0.1ex;\n"
"    padding: 0.1ex;\n"
"    border-style: solid;\n"
"    border-color: #EFF0F1;\n"
"    background-color: #bcbfc2;\n"
"    border-radius: 0.5ex;\n"
"}\n"
"\n"
"QStackedWidget\n"
"{\n"
"    border: 0.1ex transparent black;\n"
"}\n"
"\n"
"QToolBar\n"
"{\n"
"    border: 0.1ex transparent #393838;\n"
"    background: 0.1ex solid #EFF0F1;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal\n"
"{\n"
"    border-image: url(:/light/hmovetoolbar.svg);\n"
"    width = 1.6ex;\n"
"    height = 6.4ex;\n"
"}\n"
"\n"
"QToolBar::handle:vertical\n"
"{\n"
"    border-image: url(:/light/vmovetoolbar.svg);\n"
"    width = 5.4ex;\n"
"    height = 1ex;\n"
"}\n"
"\n"
"QToolBar::separator:horizontal\n"
"{\n"
"    border-image: url(:/light/hsepartoolbar.svg);\n"
"    width = 0.7ex;\n"
"    height = 6.3ex;\n"
"}\n"
"\n"
"QToolBar::separator:vertical\n"
"{\n"
"    border-image: url(:/light/vsepartoolbars.svg);\n"
"    width = 6.3ex;\n"
"    height = 0.7ex;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #31363B;\n"
"    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #EFF0F1, stop: 0.5 #eaebec);\n"
"    border-width: 0.1ex;\n"
"    border-color: #BAB9B8;\n"
"    border-style: solid;\n"
"    padding: 0.5ex;\n"
"    border-radius: 0.2ex;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: #e0e1e2;\n"
"    border-width: 0.1ex;\n"
"    border-color: #b4b4b4;\n"
"    border-style: solid;\n"
"    padding-top: 0.5ex;\n"
"    padding-bottom: 0.5ex;\n"
"    padding-left: 1ex;\n"
"    padding-right: 1ex;\n"
"    border-radius: 0.2ex;\n"
"    color: #b4b4b4;\n"
"}\n"
"\n"
"QPushButton:focus\n"
"{\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #33A4DF;\n"
"    border-style: solid;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    border-radius: 0.2ex;\n"
"    padding: 0.5ex;\n"
"    min-width: 7.5ex;\n"
"}\n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: #BAB9B8;\n"
"    border-color: #6A6969;\n"
"}\n"
"\n"
"QComboBox:hover,\n"
"QAbstractSpinBox:hover,\n"
"QLineEdit:hover,\n"
"QTextEdit:hover,\n"
"QPlainTextEdit:hover,\n"
"QAbstractView:hover,\n"
"QTreeView:hover\n"
"{\n"
"    border: 0.1ex solid #33A4DF;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QComboBox:hover:pressed,\n"
"QPushButton:hover:pressed,\n"
"QAbstractSpinBox:hover:pressed,\n"
"QLineEdit:hover:pressed,\n"
"QTextEdit:hover:pressed,\n"
"QPlainTextEdit:hover:pressed,\n"
"QAbstractView:hover:pressed,\n"
"QTreeView:hover:pressed\n"
"{\n"
"    background-color: #EFF0F1;\n"
"}\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 0.3ex;\n"
"    padding-left: 0.4ex;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #FCFCFC;\n"
"    border-radius: 0.2ex;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    selection-background-color: #33A4DF;\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 1.5ex;\n"
"\n"
"    border-left-width: 0ex;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 0.3ex;\n"
"    border-bottom-right-radius: 0.3ex;\n"
"}\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    border-image: url(:/light/down_arrow_disabled.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus\n"
"{\n"
"    border-image: url(:/light/down_arrow.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QAbstractSpinBox\n"
"{\n"
"    padding: 0.5ex;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    background-color: #D9D8D7;\n"
"    color: #31363B;\n"
"    border-radius: 0.2ex;\n"
"    min-width: 7.5ex;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button\n"
"{\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center right;\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button\n"
"{\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center left;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow,\n"
"QAbstractSpinBox::up-arrow:disabled,\n"
"QAbstractSpinBox::up-arrow:off\n"
"{\n"
"    border-image: url(:/light/up_arrow_disabled.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:hover\n"
"{\n"
"    border-image: url(:/light/up_arrow.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow,\n"
"QAbstractSpinBox::down-arrow:disabled,\n"
"QAbstractSpinBox::down-arrow:off\n"
"{\n"
"    border-image: url(:/light/down_arrow_disabled.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:hover\n"
"{\n"
"    border-image: url(:/light/down_arrow.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"    border: 0ex solid black;\n"
"}\n"
"\n"
"QTabWidget{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"/* BORDERS */\n"
"QTabWidget::pane\n"
"{\n"
"    padding: 0.5ex;\n"
"    margin: 0.1ex;\n"
"}\n"
"\n"
"QTabWidget::pane:top\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    top: -0.1ex;\n"
"}\n"
"\n"
"QTabWidget::pane:bottom\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    bottom: -0.1ex;\n"
"}\n"
"\n"
"QTabWidget::pane:left\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    right: -0.1ex;\n"
"}\n"
"\n"
"QTabWidget::pane:right\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    left: -0.1ex;\n"
"}\n"
"\n"
"QTabBar\n"
"{\n"
"    qproperty-drawBase: 0;\n"
"    left: 0.5ex; /* move to the right by 0.5ex */\n"
"    border-radius: 0.3ex;\n"
"}\n"
"\n"
"QTabBar:focus\n"
"{\n"
"    border: 0ex transparent black;\n"
"}\n"
"\n"
"QTabBar::close-button\n"
"{\n"
"    border-image: url(:/light/close.svg);\n"
"    width: 1.2ex;\n"
"    height: 1.2ex;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabBar::close-button:hover\n"
"{\n"
"    border-image: url(:/light/close-hover.svg);\n"
"    width: 1.2ex;\n"
"    height: 1.2ex;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabBar::close-button:pressed\n"
"{\n"
"    border-image: url(:/light/close-pressed.svg);\n"
"    width: 1.2ex;\n"
"    height: 1.2ex;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* TOP TABS */\n"
"QTabBar::tab:top\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    background-color: #EFF0F1;\n"
"    padding: 0.5ex;\n"
"    min-width: 5ex;\n"
"    border-top-left-radius: 0.2ex;\n"
"    border-top-right-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:top:last,\n"
"QTabBar::tab:top:only-one\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    border-right: 0.1ex solid #BAB9B8;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    background-color: #EFF0F1;\n"
"    padding: 0.5ex;\n"
"    min-width: 5ex;\n"
"    border-top-left-radius: 0.2ex;\n"
"    border-top-right-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected\n"
"{\n"
"    color: #31363B;\n"
"    background-color: #D9D8D7;\n"
"    border: 0.1ex transparent black;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    border-top-left-radius: 0.2ex;\n"
"    border-top-right-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:top:first:!selected\n"
"{\n"
"    color: #31363B;\n"
"    background-color: #D9D8D7;\n"
"    border: 0.1ex transparent black;\n"
"    border-top-left-radius: 0.2ex;\n"
"    border-top-right-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:first:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"}\n"
"\n"
"/* BOTTOM TABS */\n"
"QTabBar::tab:bottom\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    border-bottom: 0.1ex solid #BAB9B8;\n"
"    background-color: #EFF0F1;\n"
"    padding: 0.5ex;\n"
"    border-bottom-left-radius: 0.2ex;\n"
"    border-bottom-right-radius: 0.2ex;\n"
"    min-width: 5ex;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:last,\n"
"QTabBar::tab:bottom:only-one\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    border-right: 0.1ex solid #BAB9B8;\n"
"    border-bottom: 0.1ex solid #BAB9B8;\n"
"    background-color: #EFF0F1;\n"
"    padding: 0.5ex;\n"
"    border-bottom-left-radius: 0.2ex;\n"
"    border-bottom-right-radius: 0.2ex;\n"
"    min-width: 5ex;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected\n"
"{\n"
"    color: #31363B;\n"
"    background-color: #D9D8D7;\n"
"    border: 0.1ex transparent black;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    border-bottom-left-radius: 0.2ex;\n"
"    border-bottom-right-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:first:!selected\n"
"{\n"
"    color: #31363B;\n"
"    background-color: #D9D8D7;\n"
"    border: 0.1ex transparent black;\n"
"    border-bottom-left-radius: 0.2ex;\n"
"    border-bottom-right-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:first:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"}\n"
"\n"
"/* LEFT TABS */\n"
"QTabBar::tab:left\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    border-right: 0.1ex solid #BAB9B8;\n"
"    background-color: #EFF0F1;\n"
"    padding: 0.5ex;\n"
"    border-top-right-radius: 0.2ex;\n"
"    border-bottom-right-radius: 0.2ex;\n"
"    min-height: 5ex;\n"
"}\n"
"\n"
"QTabBar::tab:left:last,\n"
"QTabBar::tab:left:only-one\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    border-bottom: 0.1ex solid #BAB9B8;\n"
"    border-right: 0.1ex solid #BAB9B8;\n"
"    background-color: #EFF0F1;\n"
"    padding: 0.5ex;\n"
"    border-top-right-radius: 0.2ex;\n"
"    border-bottom-right-radius: 0.2ex;\n"
"    min-height: 5ex;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected\n"
"{\n"
"    color: #31363B;\n"
"    background-color: #D9D8D7;\n"
"    border: 0.1ex transparent black;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    border-top-right-radius: 0.2ex;\n"
"    border-bottom-right-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:first:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"}\n"
"\n"
"/* RIGHT TABS */\n"
"QTabBar::tab:right\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    background-color: #D9D8D7;\n"
"    padding: 0.5ex;\n"
"    border-top-left-radius: 0.2ex;\n"
"    border-bottom-left-radius: 0.2ex;\n"
"    min-height: 5ex;\n"
"}\n"
"\n"
"QTabBar::tab:right:last,\n"
"QTabBar::tab:right:only-one\n"
"{\n"
"    color: #31363B;\n"
"    border: 0.1ex transparent black;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    border-bottom: 0.1ex solid #BAB9B8;\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"    background-color: #D9D8D7;\n"
"    padding: 0.5ex;\n"
"    border-top-left-radius: 0.2ex;\n"
"    border-bottom-left-radius: 0.2ex;\n"
"    min-height: 5ex;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    color: #31363B;\n"
"    background-color: #54575B;\n"
"    border: 0.1ex transparent black;\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"    border-top-left-radius: 0.2ex;\n"
"    border-bottom-left-radius: 0.2ex;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:first:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    border: 0.1ex rgba(61, 173, 232, 0.1);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled\n"
"{\n"
"    border-image: url(:/light/right_arrow.svg);\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:enabled\n"
"{\n"
"    border-image: url(:/light/left_arrow.svg);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled\n"
"{\n"
"    border-image: url(:/light/right_arrow_disabled.svg);\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:disabled\n"
"{\n"
"    border-image: url(:/light/left_arrow_disabled.svg);\n"
"}\n"
"\n"
"QDockWidget\n"
"{\n"
"    background: #EFF0F1;\n"
"    border: 0.1ex solid #403F3F;\n"
"    titlebar-close-icon: url(:/light/transparent.svg);\n"
"    titlebar-normal-icon: url(:/light/transparent.svg);\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button\n"
"{\n"
"    border: 0.1ex solid transparent;\n"
"    border-radius: 0.2ex;\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"QDockWidget::float-button\n"
"{\n"
"    border-image: url(:/dark/undock.svg);\n"
"}\n"
"\n"
"QDockWidget::float-button:hover\n"
"{\n"
"    border-image: url(:/dark/undock-hover.svg) ;\n"
"}\n"
"\n"
"QDockWidget::close-button\n"
"{\n"
"    border-image: url(:/dark/close.svg) ;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover\n"
"{\n"
"    border-image: url(:/dark/close-hover.svg) ;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed\n"
"{\n"
"    border-image: url(:/dark/close-pressed.svg) ;\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    background-color: #FCFCFC;\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item\n"
"{\n"
"    border-image: url(:/light/stylesheet-vline.svg) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item\n"
"{\n"
"    border-image: url(:/light/stylesheet-branch-more.svg) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item\n"
"{\n"
"    border-image: url(:/light/stylesheet-branch-end.svg) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings\n"
"{\n"
"    border-image: url(:/light/stylesheet-branch-end-closed.svg) 0;\n"
"    image: url(:/light/branch_closed.svg);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings\n"
"{\n"
"    border-image: url(:/light/stylesheet-branch-end-open.svg) 0;\n"
"    image: url(:/light/branch_open.svg);\n"
"}\n"
"\n"
"QTableView::item,\n"
"QListView::item,\n"
"QTreeView::item\n"
"{\n"
"    padding: 0.3ex;\n"
"}\n"
"\n"
"QTableView::item:!selected:hover,\n"
"QListView::item:!selected:hover,\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: rgba(61, 173, 232, 0.1);\n"
"    outline: 0;\n"
"    color: #31363B;\n"
"    padding: 0.3ex;\n"
"}\n"
"\n"
"QSlider::groove:horizontal\n"
"{\n"
"    border: 0.1ex solid #EFF0F1;\n"
"    height: 0.4ex;\n"
"    background: #9CA0A4;\n"
"    margin: 0px;\n"
"    border-radius: 0.2ex;\n"
"}\n"
"\n"
"QSlider::handle:horizontal\n"
"{\n"
"    background: #D9D8D7;\n"
"    border: 0.1ex solid #BABEC2;\n"
"    width: 1.6ex;\n"
"    height: 1.6ex;\n"
"    margin: -0.8ex 0;\n"
"    border-radius: 0.9ex;\n"
"}\n"
"\n"
"QSlider::groove:vertical\n"
"{\n"
"    border: 0.1ex solid #EFF0F1;\n"
"    width: 0.4ex;\n"
"    background: #9CA0A4;\n"
"    margin: 0ex;\n"
"    border-radius: 0.3ex;\n"
"}\n"
"\n"
"QSlider::handle:vertical\n"
"{\n"
"    background: #D9D8D7;\n"
"    border: 0.1ex solid #BABEC2;\n"
"    width: 1.6ex;\n"
"    height: 1.6ex;\n"
"    margin: 0 -0.8ex;\n"
"    border-radius: 0.9ex;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:focus,\n"
"QSlider::handle:vertical:focus\n"
"{\n"
"    border: 0.1ex solid #33A4DF;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover\n"
"{\n"
"    border: 0.1ex solid #51c2fc;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal,\n"
"QSlider::add-page:vertical\n"
"{\n"
"    background: #33A4DF;\n"
"    border-radius: 0.3ex;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal,\n"
"QSlider::sub-page:vertical\n"
"{\n"
"    background: #BABEC2;\n"
"    border-radius: 0.3ex;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"    background-color: transparent;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    border-radius: 0.2ex;\n"
"    margin: 0.3ex;\n"
"    padding: 0.5ex;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] /* only for MenuButtonPopup */\n"
"{\n"
"    padding-right: 2ex; /* make way for the popup button */\n"
"}\n"
"\n"
"QToolButton[popupMode=\"2\"] /* only for InstantPopup */\n"
"{\n"
"    padding-right: 1ex; /* make way for the popup button */\n"
"}\n"
"\n"
"QToolButton::menu-indicator\n"
"{\n"
"    border-image: url(:/light/down_arrow.svg);\n"
"    top: -0.7ex; left: -0.2ex; /* shift it a bit */\n"
"    width = 0.9ex;\n"
"    height = 0.6ex;\n"
"}\n"
"\n"
"QToolButton::menu-arrow\n"
"{\n"
"    border-image: url(:/light/down_arrow.svg);\n"
"    width = 0.9ex;\n"
"    height = 0.6ex;\n"
"}\n"
"\n"
"QToolButton:hover,\n"
"QToolButton::menu-button:hover\n"
"{\n"
"    background-color: transparent;\n"
"    border: 0.1ex solid #33A4DF;\n"
"}\n"
"\n"
"QToolButton:checked,\n"
"QToolButton:pressed,\n"
"QToolButton::menu-button:pressed\n"
"{\n"
"    background-color: #47b8fc;\n"
"    border: 0.1ex solid #47b8fc;\n"
"    padding: 0.5ex;\n"
"}\n"
"\n"
"QToolButton::menu-button\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    /* 1ex width + 0.4ex for border + no text = 2ex allocated above */\n"
"    width: 1ex;\n"
"    padding: 0.5ex;\n"
"    outline: none;\n"
"}\n"
"\n"
"QToolButton::menu-arrow:open\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QPushButton::menu-indicator\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    left: 0.8ex;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    gridline-color: #BAB9B8;\n"
"    background-color: #FCFCFC;\n"
"}\n"
"\n"
"\n"
"QTableView,\n"
"QHeaderView\n"
"{\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTableView::item:pressed\n"
"{\n"
"    background: #33A4DF;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QTableView::item:selected:active\n"
"{\n"
"    background: #33A4DF;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QTableView::item:selected:hover\n"
"{\n"
"    background-color: #47b8f3;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QListView::item:pressed,\n"
"QTreeView::item:pressed\n"
"{\n"
"    background: #3daee9;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QTreeView::item:selected:active,\n"
"QListView::item:selected:active\n"
"{\n"
"    background: #3daee9;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QListView::item:selected:hover,\n"
"QTreeView::item:selected:hover\n"
"{\n"
"    background-color: #51c2fc;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"\n"
"QHeaderView\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    border: 0.1ex transparent;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    color: #31363B;\n"
"    padding: 0.5ex;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: transparent;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal::first, QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: transparent;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"\n"
" {\n"
"    color: black;\n"
"    background-color: #b9dae7;\n"
" }\n"
"\n"
" /* style the sort indicator */\n"
"QHeaderView::down-arrow\n"
"{\n"
"    image: url(:/light/down_arrow.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow\n"
"{\n"
"    image: url(:/light/up_arrow.svg);\n"
"}\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    border: 0.1ex transparent #BAB9B8;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QToolBox\n"
"{\n"
"    padding: 0.5ex;\n"
"    border: 0.1ex transparent black;\n"
"}\n"
"\n"
"QToolBox:selected\n"
"{\n"
"    background-color: #EFF0F1;\n"
"    border-color: #33A4DF;\n"
"}\n"
"\n"
"QToolBox:hover\n"
"{\n"
"    border-color: #33A4DF;\n"
"}\n"
"\n"
"QStatusBar::item\n"
"{\n"
"    border: 0px transparent dark;\n"
"}\n"
"\n"
"QSplitter::handle\n"
"{\n"
"    border: 0.1ex dashed #BAB9B8;\n"
"}\n"
"\n"
"QSplitter::handle:hover\n"
"{\n"
"    background-color: #787876;\n"
"    border: 0.1ex solid #BAB9B8;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal\n"
"{\n"
"    width: 0.1ex;\n"
"}\n"
"\n"
"QSplitter::handle:vertical\n"
"{\n"
"    height: 0.1ex;\n"
"}\n"
"\n"
"QProgressBar:horizontal\n"
"{\n"
"    background-color: #BABEC2;\n"
"    border: 0.1ex solid #EFF0F1;\n"
"    border-radius: 0.3ex;\n"
"    height: 0.5ex;\n"
"    text-align: right;\n"
"    margin-top: 0.5ex;\n"
"    margin-bottom: 0.5ex;\n"
"    margin-right: 5ex;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QProgressBar::chunk:horizontal\n"
"{\n"
"    background-color: #33A4DF;\n"
"    border: 0.1ex transparent;\n"
"    border-radius: 0.3ex;\n"
"}\n"
"\n"
"QAbstractSpinBox\n"
"{\n"
"    background-color: #EFF0F1;\n"
"}\n"
"\n"
"QSpinBox,\n"
"QDoubleSpinBox\n"
"{\n"
"    padding-right: 1.5ex;\n"
"}\n"
"\n"
"QSpinBox::up-button,\n"
"QDoubleSpinBox::up-button\n"
"{\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: right top;\n"
"\n"
"    width: 1.6ex;\n"
"    border-width: 0.1ex;\n"
"}\n"
"\n"
"QSpinBox::up-arrow,\n"
"QDoubleSpinBox::up-arrow\n"
"{\n"
"    border-image: url(:/light/up_arrow.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:hover,\n"
"QSpinBox::up-arrow:pressed,\n"
"QDoubleSpinBox::up-arrow:hover,\n"
"QDoubleSpinBox::up-arrow:pressed\n"
"{\n"
"    border-image: url(:/light/up_arrow-hover.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:disabled,\n"
"QSpinBox::up-arrow:off,\n"
"QDoubleSpinBox::up-arrow:disabled,\n"
"QDoubleSpinBox::up-arrow:off\n"
"{\n"
"   border-image: url(:/light/up_arrow_disabled.svg);\n"
"}\n"
"\n"
"QSpinBox::down-button,\n"
"QDoubleSpinBox::down-button\n"
"{\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: right bottom;\n"
"\n"
"    width: 1.6ex;\n"
"    border-width: 0.1ex;\n"
"}\n"
"\n"
"QSpinBox::down-arrow,\n"
"QDoubleSpinBox::down-arrow\n"
"{\n"
"    border-image: url(:/light/down_arrow.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QSpinBox::down-arrow:hover,\n"
"QSpinBox::down-arrow:pressed,\n"
"QDoubleSpinBox::down-arrow:hover,\n"
"QDoubleSpinBox::down-arrow:pressed\n"
"{\n"
"    border-image: url(:/light/down_arrow-hover.svg);\n"
"    width: 0.9ex;\n"
"    height: 0.6ex;\n"
"}\n"
"\n"
"QSpinBox::down-arrow:disabled,\n"
"QSpinBox::down-arrow:off,\n"
"QDoubleSpinBox::down-arrow:disabled,\n"
"QDoubleSpinBox::down-arrow:off\n"
"{\n"
"   border-image: url(:/light/down_arrow_disabled.svg);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border: 0.1ex solid #3daef3;\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QPushButton:focus\n"
"{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #4cbdff, stop: 0.5 #33a4e8);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:focus:hover\n"
"{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #bedfec, stop: 0.5 #b9dae7);\n"
"    color: #31363B;\n"
"}\n"
"\n"
"QPushButton:focus:pressed,\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #bedfec, stop: 0.5 #b9dae7);\n"
"    color: #31363B;\n"
"}\n"
"")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 191, 101))
        self.label_2.setStyleSheet("QLabel{\n"
"    border:1px solid #4cbdff;\n"
"}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\pannar.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 120, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    border: 1px solid #4cbdff;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.browes_btn = QtWidgets.QPushButton(Form)
        self.browes_btn.setGeometry(QtCore.QRect(320, 170, 87, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.browes_btn.setFont(font)
        self.browes_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.browes_btn.setStyleSheet("QPushButton{\n"
"\n"
"    border: 1px solid #4cbdff;\n"
"}")
        self.browes_btn.setObjectName("browes_btn")
        self.save_location_LD = QtWidgets.QLineEdit(Form)
        self.save_location_LD.setGeometry(QtCore.QRect(10, 180, 301, 31))
        self.save_location_LD.setStyleSheet("QLineEdit{\n"
"    border: 1px solid #008bff;\n"
"}\n"
"\n"
"")
        self.save_location_LD.setObjectName("save_location_LD")
        self.export_btn = QtWidgets.QPushButton(Form)
        self.export_btn.setGeometry(QtCore.QRect(160, 230, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.export_btn.setFont(font)
        self.export_btn.setStyleSheet("QPushButton{\n"
"    border: 2px solid #4cbdff;\n"
"}")
        self.export_btn.setObjectName("export_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.save_location_LD, self.browes_btn)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "اختر مكان الحفظ"))
        self.browes_btn.setText(_translate("Form", "استعراض"))
        self.export_btn.setText(_translate("Form", "تصدير"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Exporting_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
